//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCSN.MF1759.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceVN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceVN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HCSN.MF1759.Domain.Common.Resources.ResourceVN", typeof(ResourceVN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa.
        /// </summary>
        public static string Error_CannotDelete {
            get {
                return ResourceManager.GetString("Error_CannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nguyên giá không được để trống.
        /// </summary>
        public static string Error_CostNotEmpty {
            get {
                return ResourceManager.GetString("Error_CostNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phòng ban không được để trống.
        /// </summary>
        public static string Error_DepartmentCodeNotEmpty {
            get {
                return ResourceManager.GetString("Error_DepartmentCodeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên phòng ban không được để trống.
        /// </summary>
        public static string Error_DepartmentNameNotEmpty {
            get {
                return ResourceManager.GetString("Error_DepartmentNameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy phòng ban.
        /// </summary>
        public static string Error_DepartmentNotFound1 {
            get {
                return ResourceManager.GetString("Error_DepartmentNotFound1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỷ lệ hao mòn phải bằng 1/Số năm sử dụng.
        /// </summary>
        public static string Error_DepreciationRateError {
            get {
                return ResourceManager.GetString("Error_DepreciationRateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉ lệ hao mòn không được để trống.
        /// </summary>
        public static string Error_DepreciationRateNotEmpty {
            get {
                return ResourceManager.GetString("Error_DepreciationRateNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị hao mòn năm phải bằng (nguyên giá * tỷ lệ hao mòn).
        /// </summary>
        public static string Error_DepreciationValueYearError {
            get {
                return ResourceManager.GetString("Error_DepreciationValueYearError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉ lệ hao mòn năm không được để trống.
        /// </summary>
        public static string Error_DepreciationValueYearNotEmpty {
            get {
                return ResourceManager.GetString("Error_DepreciationValueYearNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày chứng từ phải nhỏ hơn ngày điều chuyển.
        /// </summary>
        public static string Error_DocumentDateMustLessThenTransferDate {
            get {
                return ResourceManager.GetString("Error_DocumentDateMustLessThenTransferDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn phòng ban điều chuyển khác với phòng ban hiện tại.
        /// </summary>
        public static string Error_DuplicateDepartmentBeforeAndAfter {
            get {
                return ResourceManager.GetString("Error_DuplicateDepartmentBeforeAndAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phòng ban {code} đã tồn tại.
        /// </summary>
        public static string Error_DuplicateDepartmentCode {
            get {
                return ResourceManager.GetString("Error_DuplicateDepartmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã loại tài sản {code} đã tồn tại.
        /// </summary>
        public static string Error_DuplicateFixedAssetCategoryCode {
            get {
                return ResourceManager.GetString("Error_DuplicateFixedAssetCategoryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tài sản {code} đã tồn tại.
        /// </summary>
        public static string Error_DuplicateFixedAssetCode {
            get {
                return ResourceManager.GetString("Error_DuplicateFixedAssetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã chứng từ {code} đã tồn tại.
        /// </summary>
        public static string Error_DuplicateTransferDocumentCode {
            get {
                return ResourceManager.GetString("Error_DuplicateTransferDocumentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã loại tài sản không được để trống.
        /// </summary>
        public static string Error_FixedAssetCategoryCodeNotEmpty {
            get {
                return ResourceManager.GetString("Error_FixedAssetCategoryCodeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên loại tài sản không được để trống.
        /// </summary>
        public static string Error_FixedAssetCategoryNameNotEmpty {
            get {
                return ResourceManager.GetString("Error_FixedAssetCategoryNameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy mã loại tài sản.
        /// </summary>
        public static string Error_FixedAssetCategoryNotFound {
            get {
                return ResourceManager.GetString("Error_FixedAssetCategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tài sản không được để trống.
        /// </summary>
        public static string Error_FixedAssetCodeNotEmpty {
            get {
                return ResourceManager.GetString("Error_FixedAssetCodeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa tài sản do đã có chứng từ phát sinh
        ///- Chứng từ điều chuyển {code} ({date}).
        /// </summary>
        public static string Error_FixedAssetDelete {
            get {
                return ResourceManager.GetString("Error_FixedAssetDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài sản không được để trống.
        /// </summary>
        public static string Error_FixedAssetNameNotEmpty {
            get {
                return ResourceManager.GetString("Error_FixedAssetNameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi nhập từ người dùng.
        /// </summary>
        public static string Error_Input {
            get {
                return ResourceManager.GetString("Error_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số năm sử dụng không được để trống.
        /// </summary>
        public static string Error_LifeTimeNotEmpty {
            get {
                return ResourceManager.GetString("Error_LifeTimeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không được truyền danh sách rỗng.
        /// </summary>
        public static string Error_NotEmptyList {
            get {
                return ResourceManager.GetString("Error_NotEmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy tài nguyên.
        /// </summary>
        public static string Error_Notfound {
            get {
                return ResourceManager.GetString("Error_Notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng phải lớn hơn hoặc bằng 0.
        /// </summary>
        public static string Error_PositiveQuantity {
            get {
                return ResourceManager.GetString("Error_PositiveQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày mua không được để trống.
        /// </summary>
        public static string Error_PurchaseDate {
            get {
                return ResourceManager.GetString("Error_PurchaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày mua phải nhỏ hơn ngày sử dụng.
        /// </summary>
        public static string Error_PurchaseDateMustLessThenStartUsingDate {
            get {
                return ResourceManager.GetString("Error_PurchaseDateMustLessThenStartUsingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng không được để trống.
        /// </summary>
        public static string Error_QuantityNotEmpty {
            get {
                return ResourceManager.GetString("Error_QuantityNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày bắt đầu sử dụng không được để trống.
        /// </summary>
        public static string Error_StartUsingDate {
            get {
                return ResourceManager.GetString("Error_StartUsingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian điều chuyển phải lớn hơn thời gian điều chuyển trước đó.
        /// </summary>
        public static string Error_TransferDateError {
            get {
                return ResourceManager.GetString("Error_TransferDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có chứng từ phát sinh phía sau. Bạn không thể xóa chứng từ này.
        ///- Chứng từ điều chuyển {code} ({date}).
        /// </summary>
        public static string ErrorDelete_TransferDateError {
            get {
                return ResourceManager.GetString("ErrorDelete_TransferDateError", resourceCulture);
            }
        }
    }
}
